import React, { useState } from 'react';
import { Brain, AlertCircle, ShieldAlert, CheckCircle2, Download, Activity, RefreshCw } from 'lucide-react';
import axios from 'axios';
import { Modal } from './Modal';
import { FormInput } from './FormInput';
import { Dropdown } from './Dropdown';
import { Button } from './Button';
import { Badge } from './Badge';
import { useToast } from '../context/ToastContext';
import { useAuth } from '../context/AuthContext';
export const AIDiagnosisModal = ({ isOpen, onClose, onViewPDF }) => {
    const { user } = useAuth();
    const { showToast } = useToast();
    const [symptoms, setSymptoms] = useState('');
    const [age, setAge] = useState(user?.age || 34);
    const [gender, setGender] = useState(user?.gender || 'Male');
    const [medicalHistory, setMedicalHistory] = useState(user?.medicalHistory?.join(', ') || 'Mild asthma, seasonal allergies');
    const [existingDiseases, setExistingDiseases] = useState(user?.existingDiseases?.join(', ') || 'None');
    const [loading, setLoading] = useState(false);
    const [report, setReport] = useState(null);
    const handleDiagnose = async (e) => {
        e.preventDefault();
        if (!symptoms.trim()) {
            showToast('Input Required', 'Please enter your symptoms to run AI diagnosis.', 'warning');
            return;
        }
        setLoading(true);
        try {
            const token = localStorage.getItem('carexpert_token');
            const res = await axios.post('/api/ai/diagnose', {
                symptoms,
                age,
                gender,
                medicalHistory,
                existingDiseases
            }, {
                headers: { Authorization: `Bearer ${token}` }
            });
            if (res.data.success) {
                setReport(res.data.report);
                showToast('AI Diagnosis Ready', 'Triage assessment complete.', 'success');
            }
        }
        catch (err) {
            showToast('AI Service Error', err.response?.data?.message || 'Could not complete AI analysis.', 'error');
        }
        finally {
            setLoading(false);
        }
    };
    const handleReset = () => {
        setReport(null);
        setSymptoms('');
    };
    const riskBadgeColors = {
        Low: 'success',
        Moderate: 'warning',
        High: 'danger',
        Critical: 'danger'
    };
    return (<Modal isOpen={isOpen} onClose={onClose} title="CareXpertAI Diagnostic Triage" maxWidth="2xl">
      {!report ? (<form onSubmit={handleDiagnose} className="space-y-5">
          {/* Medical Disclaimer & Trial Notice Banner */}
          <div className="bg-amber-50 border border-amber-200 p-3.5 rounded-xl text-xs text-amber-900 space-y-1.5 shadow-2xs">
            <div className="flex items-center gap-2 font-bold text-amber-800">
              <ShieldAlert className="w-4 h-4 text-amber-600 shrink-0"/>
              <span>Important Medical Disclaimer & Trial Project Notice</span>
            </div>
            <p className="text-[11px] leading-relaxed text-amber-900/90">
              <strong>1. Not an Official Medical Report:</strong> This AI diagnostic triage generated by Gemini is <em>not an official medical diagnosis</em> or clinical prescription.
              <br />
              <strong>2. Consult a Licensed Doctor:</strong> Do not rely on this report for self-diagnosis or emergency treatment. Always consult a certified physician or doctor for actual medical care.
              <br />
              <strong>3. Trial Project:</strong> CareXpertAI is a trial project developed strictly for testing and demonstration purposes.
            </p>
          </div>

          <div className="bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-100 p-4 rounded-2xl flex items-start gap-3">
            <Brain className="w-5 h-5 text-blue-600 shrink-0 mt-0.5"/>
            <p className="text-xs text-slate-700 leading-relaxed">
              Enter active patient symptoms and health history. Our AI model will process differential triage probabilities, risk levels, and recommended medical specialists.
            </p>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-1.5">
              Describe Symptoms & Duration <span className="text-rose-600">*</span>
            </label>
            <textarea rows={3} value={symptoms} onChange={(e) => setSymptoms(e.target.value)} placeholder="e.g. Tightness in chest after climbing stairs, persistent dry cough, fatigue for 3 days" className="w-full bg-slate-50 border border-slate-200 focus:border-blue-500 focus:bg-white text-slate-800 placeholder-slate-400 text-sm rounded-xl p-3.5 outline-none transition-all focus:ring-2 focus:ring-blue-500" required/>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormInput label="Patient Age" type="number" value={age} onChange={(e) => setAge(Number(e.target.value))}/>
            <Dropdown label="Gender" value={gender} onChange={(e) => setGender(e.target.value)} options={[
                { value: 'Male', label: 'Male' },
                { value: 'Female', label: 'Female' },
                { value: 'Other', label: 'Other / Unspecified' }
            ]}/>
          </div>

          <FormInput label="Medical History / Allergies" value={medicalHistory} onChange={(e) => setMedicalHistory(e.target.value)} placeholder="e.g. Asthma, Penicillin allergy"/>

          <FormInput label="Pre-existing Diseases / Conditions" value={existingDiseases} onChange={(e) => setExistingDiseases(e.target.value)} placeholder="e.g. Hypertension, Diabetes Type II"/>

          <div className="pt-2 flex items-center justify-end gap-3 border-t border-slate-100">
            <Button onClick={onClose} type="button" variant="ghost">
              Cancel
            </Button>
            <Button type="submit" isLoading={loading} variant="primary" className="bg-blue-600 hover:bg-blue-700 text-white shadow-xs" icon={<Brain className="w-4 h-4"/>}>
              Generate AI Triage Report
            </Button>
          </div>
        </form>) : (<div className="space-y-6">
          {/* Header Summary */}
          <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200 space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 pb-3">
              <div className="flex items-center gap-2">
                <Brain className="w-5 h-5 text-blue-600"/>
                <h3 className="font-bold text-slate-800 text-base">AI Clinical Triage Results</h3>
              </div>
              <Badge variant={riskBadgeColors[report.riskLevel] || 'warning'}>
                Risk Level: {report.riskLevel}
              </Badge>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs text-slate-600">
              <div>
                <span className="text-slate-400">Recommended Specialist: </span>
                <span className="font-bold text-blue-600">{report.recommendedSpecialist}</span>
              </div>
              <div>
                <span className="text-slate-400">Patient: </span>
                <span className="font-semibold text-slate-800">{report.patientName} ({report.age} yrs, {report.gender})</span>
              </div>
            </div>
          </div>

          {/* Suspected Diseases Differential Analysis */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">Possible Diseases & Probabilities</h4>
            <div className="space-y-2">
              {report.possibleDiseases.map((d, i) => (<div key={i} className="bg-white p-4 rounded-xl border border-slate-200 space-y-1 shadow-2xs">
                  <div className="flex items-center justify-between text-sm">
                    <span className="font-bold text-slate-800">{d.name}</span>
                    <span className="font-bold text-blue-700 bg-blue-50 px-2 py-0.5 rounded-md border border-blue-200 text-xs">
                      {d.probability}
                    </span>
                  </div>
                  <p className="text-xs text-slate-600">{d.description}</p>
                </div>))}
            </div>
          </div>

          {/* Recommended Tests & Precautions */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
            <div className="bg-white p-4 rounded-xl border border-slate-200 space-y-2 shadow-2xs">
              <h5 className="font-bold text-slate-800 flex items-center gap-1.5">
                <Activity className="w-4 h-4 text-blue-600"/>
                <span>Recommended Diagnostic Tests</span>
              </h5>
              <ul className="list-disc list-inside space-y-1 text-slate-600">
                {report.recommendedTests.map((t, i) => <li key={i}>{t}</li>)}
              </ul>
            </div>

            <div className="bg-white p-4 rounded-xl border border-slate-200 space-y-2 shadow-2xs">
              <h5 className="font-bold text-slate-800 flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-emerald-600"/>
                <span>Basic Precautions</span>
              </h5>
              <ul className="list-disc list-inside space-y-1 text-slate-600">
                {report.basicPrecautions.map((p, i) => <li key={i}>{p}</li>)}
              </ul>
            </div>
          </div>

          {/* Disclaimer & Trial Project Warning */}
          <div className="bg-rose-50 border border-rose-200 p-4 rounded-xl text-xs text-rose-900 space-y-1.5 shadow-2xs">
            <div className="flex items-center gap-2 font-bold text-rose-800">
              <AlertCircle className="w-4 h-4 text-rose-600 shrink-0"/>
              <span>DISCLAIMER: NOT AN OFFICIAL MEDICAL REPORT (TRIAL PROJECT)</span>
            </div>
            <p className="text-[11px] leading-relaxed text-rose-800">
              This summary is an AI triage prediction generated by CareXpertAI (a <strong>trial project</strong>) for demonstration purposes only. It is <strong>NOT an official medical diagnosis</strong> or clinical prescription. Always <strong>consult a licensed doctor or healthcare provider</strong> for accurate diagnosis, medical evaluation, and treatment decisions.
            </p>
          </div>

          {/* Footer Actions */}
          <div className="flex flex-wrap items-center justify-between gap-3 pt-2 border-t border-slate-100">
            <Button onClick={handleReset} variant="outline" size="sm" icon={<RefreshCw className="w-3.5 h-3.5"/>}>
              Analyze New Symptoms
            </Button>

            <div className="flex gap-2">
              {onViewPDF && (<Button onClick={() => onViewPDF(report.id)} variant="primary" size="sm" className="bg-blue-600 hover:bg-blue-700 text-white shadow-xs" icon={<Download className="w-3.5 h-3.5"/>}>
                  Download Report PDF
                </Button>)}
              <Button onClick={onClose} variant="secondary" size="sm">
                Close
              </Button>
            </div>
          </div>
        </div>)}
    </Modal>);
};
